//Todo
export const ADD_TODO = 'ADD_TODO';
export const REMOVE_TODO = 'REMOVE_TODO';
export const FETCH_USERS_SUCCESS = 'FETCH_USERS_SUCCESS';
export const FETCH_ONE_USER_SUCCESS = 'FETCH_ONE_USER_SUCCESS';